search models by resources
VRK-YTI/yti-datamodel-api pull request #265
Opened 2023-12-28 07:36 UTC by urhot

Search results will now also find models if their resources match the keyword. This is done by performing an additional search, and combining the search results.

* search-models will return `ModelSearchResultDTO`, which adds matching resources to the search result in addition to the model data
* matching keywords will be highlighted in the search result
* `IndexBase` base class now contains `highlights` property
* opensearch queries have been rearranged (`must`/`should`), hopefully for more correct behaviour

Cut down example of the result:
`/v2/frontend/search-models?pageSize=50&searchResources=true&sortLang=fi&status=VALID&query=test`
```json
{
  "responseObjects": [
    {
      "id": "https://iri.suomi.fi/model/test/1.0.0/",
      "uri": "https://iri.suomi.fi/model/test/1.0.0/",
      "label": {
        "fi": "Test model"
      },
      "status": "VALID",
      "highlights": {
        "label.fi.keyword": [
          "<em>Test model</em>"
        ],
        "label.fi": [
          "<em>Test model</em>"
        ]
      },
      "matchingResources": [
        {
          "id": "https://iri.suomi.fi/model/test/1.0.0/testattribute",
          "uri": "https://iri.suomi.fi/model/test/testattribute",
          "label": {
            "fi": "Test attribute"
          },
          "status": "DRAFT",
          "highlights": {
            "label.fi.keyword": [
              "<b>Test attribute</b>"
            ],
            "label.fi": [
              "<b>Test attribute</b>"
            ]
          }
        }
      ]
    }
  ]
}

```

2023-12-28 08:05 UTC, topirissanen-atoz approved these changes

2023-12-28 08:37 UTC, tomiviljanen approved these changes

2024-01-02 06:46 UTC, kkyttala requested changes

2024-01-02 06:46 UTC, kkyttala commented on src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
> +                .map(DataModelURI::getGraphURI)
This mapping is redundant, because mapped id (starting at line 82) is graph's URI

2024-01-02 06:46 UTC, kkyttala commented on src/main/java/fi/vm/yti/datamodel/api/v2/service/SearchIndexService.java
> +                        return id.equals(searchResult.getId());
Mapping could be simplified by using response object's versionIri field

2024-01-08 10:11 UTC, kkyttala approved these changes

2024-01-12 07:52 UTC, merged